### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-crab#2]
Are there any images we can use on the blog?

**Comment by grace-ac** [comment]
Yes! I got a ton from Pam and I took a bunch when I was there for the final sampling. I'll sort through and pick some of the best and put in a google drive folder.

**Comment by sr320** [comment]
Just dump them all in the images directory - (you can also pick some out)

**Comment by grace-ac** [comment]
Wait, where can I find this directory?

**Comment by sr320** [comment]
https://github.com/RobertsLab/resources/wiki/Digital-Media

These would fall under candid..
